int main(void) {
  int b;
  int a = 1;
  a = a * 2;
  b = a = a;
  int c = 0;
  // !a = 3; gives error
  a+3; !a;
  return a;
}

/*
Program(
  Function(
    name='main'
    body=(
      Declaration(
        name='b')
      Declaration(
        name='a'
        Constant(1)
      )
      Expression(
        Assignment(
          Var(name='a')
          Binary(*,
            Var(name='a')
            Constant(2)
          )
        )
      )
      Expression(
        Assignment(
          Var(name='b')
          Assignment(
            Var(name='a')
            Var(name='a')
          )
        )
      )
      Declaration(
        name='c'
        Constant(0)
      )
      Expression(
        Binary(+,
          Var(name='a')
          Constant(3)
        )
      )
      Expression(
        Unary(!
          Var(name='a')
        )
      )
      Return(
        Constant(0)
      )
    )
  )
)
Program(
  Function(
    name='main'
    body=(
      Declaration(
        name='b.0')
      Declaration(
        name='a.1'
        Constant(1)
      )
      Expression(
        Assignment(
          Var(name='a.1')
          Binary(*,
            Var(name='a.1')
            Constant(2)
          )
        )
      )
      Expression(
        Assignment(
          Var(name='b.0')
          Assignment(
            Var(name='a.1')
            Var(name='a.1')
          )
        )
      )
      Declaration(
        name='c.2'
        Constant(0)
      )
      Expression(
        Binary(+,
          Var(name='a.1')
          Constant(3)
        )
      )
      Expression(
        Unary(!
          Var(name='a.1')
        )
      )
      Return(
        Constant(0)
      )
    )
  )
)
*/